name: "Validate everything"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  QUAY_IO_USERNAME: shepmaster

jobs:
  build_compiler_containers:
    name: "Build ${{ matrix.channel }} compiler container"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel: [stable, beta, nightly]

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Build and push container"
        uses: docker/build-push-action@v1
        with:
          username: ${{ env.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
          registry: quay.io
          repository: shepmaster/rust-playground-ci-rust-${{ matrix.channel }}
          tags: ${{ github.run_id }}
          path: compiler/base/
          build_args: channel=${{ matrix.channel }}
          always_pull: true
          cache_froms: shepmaster/rust-playground-ci-rust-${{ matrix.channel }}:latest
          labels: quay.expires-after=1w
